import type { TerminoGlosario } from '@/types/ayuda';

export const glosario: TerminoGlosario[] = [
  { termino: 'Acompañante', definicion: 'Quien valora al colaborador en crecimiento en un ciclo: puede ser autoevaluación, el líder, un par (mismo líder), o un colaborador a cargo.' },
  { termino: 'Acuerdo de crecimiento', definicion: 'Los compromisos que quedan de la sesión de retroalimentación (del colaborador y de la empresa), firmados por ambas partes con casilla + fecha.' },
  { termino: 'Alerta', definicion: 'Aviso automático de una fecha próxima a vencer: contrato, SST (examen/certificación/EPP), formación, Ciclo de Crecimiento o cultura (cumpleaños, aniversario).' },
  { termino: 'Brief de retroalimentación', definicion: 'Documento de preparación que el líder escribe antes de dar retroalimentación a su colaborador. Privado, solo lo ve quien lo escribe y Talento Humano.' },
  { termino: 'Cargo', definicion: 'El puesto de trabajo, con su propio perfil de exigencias (formación, habilidades, experiencia) definido en Administración → Cargos.' },
  { termino: 'Certificado laboral', definicion: 'Documento PDF que certifica la vinculación de una persona con la empresa (cargo, tipo de contrato, fecha de ingreso y, opcionalmente, salario). Se genera al momento desde la ficha del colaborador → Documentos.' },
  { termino: 'Ciclo de Crecimiento', definicion: 'Período (normalmente semestral) durante el cual se valoran Hacer y Deber. Ser y Saber no dependen de un ciclo, se verifican de forma continua.' },
  { termino: 'Colaborador a cargo', definicion: 'Persona que reporta directamente al colaborador en crecimiento — uno de los tipos de Acompañante en el Círculo de Crecimiento.' },
  { termino: 'Contrato', definicion: 'Archivo del contrato laboral de una persona, cargado en su ficha → Documentos, junto con su salario — que es la fuente que usa el certificado laboral.' },
  { termino: 'Cuaderno personal (Mi cuaderno)', definicion: 'Espacio de notas privadas del colaborador sobre su propio aprendizaje, dentro de Nexa → Formación. Nadie más lo puede ver, ni admin_th.' },
  { termino: 'Deber', definicion: 'Dimensión del comportamiento cultural/actitudinal de una persona, valorada por ciclo por varios tipos de Acompañante.' },
  { termino: 'Documentos (del colaborador)', definicion: 'Pantalla en la ficha del colaborador con la hoja de vida (archivo), el contrato y el generador del certificado laboral. Acceso exclusivo de admin_th y el propio colaborador.' },
  { termino: 'EPP', definicion: 'Elementos de Protección Personal — equipo de seguridad exigido según el cargo (ej. casco, guantes, arnés).' },
  { termino: 'Guía del Flow', definicion: 'Instrumento de autoconocimiento (dimensión Ser): talentos naturales, propósito y aspectos organizados en 4 bloques, diseñado por FlowAndo.' },
  { termino: 'Hacer', definicion: 'Dimensión del desempeño en comportamientos observables de una persona, valorada por ciclo.' },
  { termino: 'Hoja de vida', definicion: 'Tiene dos sentidos en el sistema: (1) el archivo del CV, cargado en Documentos; (2) el registro de formación/cursos/certificaciones con vencimiento, en la pantalla "Hoja de vida y certificaciones". Son pantallas distintas.' },
  { termino: 'Inducción (Plan de)', definicion: 'Checklist de puntos que debe cubrir una persona al ingresar o cambiar de cargo: comunes (propósito, valores) + específicos del cargo (funciones, riesgos, EPP). Se genera automáticamente y se marca cumplido desde la ficha del colaborador.' },
  { termino: 'Índice', definicion: 'El número que resume el resultado de Hacer o Deber de una persona en un ciclo, del cual se deriva el semáforo.' },
  { termino: 'Insignia', definicion: 'Reconocimiento visual que se puede otorgar junto con puntos en Nexa.' },
  { termino: 'Mensaje directo', definicion: 'Chat privado 1 a 1 entre dos personas de la empresa, distinto del feed corporativo (que es de difusión general).' },
  { termino: 'Nexa', definicion: 'El módulo de cultura y formación: feed corporativo, cursos gamificados, reconocimientos, simulacros, directorio de aliados, asistente de IA y cuaderno personal.' },
  { termino: 'Notificación', definicion: 'Aviso dirigido a una persona (ej. una fecha próxima a vencer), generado automáticamente. Se ve en el ícono de sobre del encabezado y en la pantalla Notificaciones.' },
  { termino: 'Organigrama', definicion: 'La jerarquía de la empresa (quién le reporta a quién). De ahí se deduce automáticamente quién acompaña a quién.' },
  { termino: 'Par', definicion: 'Colaborador que comparte el mismo líder directo que el colaborador en crecimiento — uno de los tipos de Acompañante.' },
  { termino: 'PDI (Plan de Desarrollo Individual)', definicion: 'El entregable central del Encuentro de Crecimiento: acciones de desarrollo para cerrar una brecha, con su origen (Hacer, Deber, Saber, Ser o mixto) y estado.' },
  { termino: 'Ponderación', definicion: 'El peso (%) que tiene cada tipo de Acompañante (líder, pares, colaboradores a cargo) en el resultado final de un ciclo. Se configura antes de abrir el ciclo.' },
  { termino: 'Reacción (Me gusta)', definicion: 'Marca que cualquier persona puede dejar en una publicación del feed corporativo.' },
  { termino: 'Reconocimiento', definicion: 'Puntos y/o insignia que admin_th o un líder otorgan a una persona en Nexa, con un motivo.' },
  { termino: 'Ruta de formación', definicion: 'Curso asignado a una persona (directamente o por cargo) dentro de Nexa → Formación y SST.' },
  { termino: 'Saber', definicion: 'Dimensión que compara lo que exige el cargo (formación, habilidades, certificaciones, experiencia) contra lo que tiene la persona.' },
  { termino: 'Semáforo', definicion: 'Clasificación Alto / Medio / Bajo, calculada automáticamente a partir del índice de Hacer o Deber.' },
  { termino: 'Ser', definicion: 'Dimensión de autoconocimiento de la persona (talentos, propósito), explorada mediante la Guía del Flow. Se registra de forma narrativa y por puntaje (1-5) en cada aspecto.' },
  { termino: 'SST', definicion: 'Seguridad y Salud en el Trabajo — exámenes, certificaciones, EPP y protocolos de riesgo laboral.' },
  { termino: 'Verificación de Saber', definicion: 'El proceso de marcar, ítem por ítem, si una persona Cumple, Cumple Parcial o No cumple lo que exige su cargo en formación, habilidades, certificaciones y experiencia.' },
];
